version: 2

# Global options
timeout: 5m
modules-download-mode: readonly

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
    - .git
    - coverage
    - test_results

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: function-result-limit
        arguments: [3]
      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [15]
  
  cyclop:
    max-complexity: 15
    package-average: 10.0
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 15
  
  funlen:
    lines: 100
    statements: 50
  
  lll:
    line-length: 120
  
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  dupl:
    threshold: 100
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "10"
      - "100"
      - "1000"
  
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - ok
      - i
      - j
      - k
      - v
      - db
      - tx
      - ctx
  
  interfacebloat:
    max: 10
  
  maintidx:
    under: 20
  
  unparam:
    check-exported: true
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 4

linters:
  enable:
    # Core default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Style and formatting
    - revive
    - misspell
    - godot
    - whitespace
    
    # Code complexity
    - cyclop
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - maintidx
    
    # Line length
    - lll
    
    # Error handling
    - errorlint
    - wrapcheck
    - nilerr
    
    # Security
    - gosec
    
    # Performance
    - prealloc
    - unconvert
    
    # Code duplication
    - dupl
    
    # Magic numbers
    - mnd
    
    # Variable naming
    - varnamelen
    - predeclared
    
    # Interface bloat
    - interfacebloat
    
    # Testing
    - testifylint
    
    # Unused parameters
    - unparam
    
    # Naked returns
    - nakedret
    
    # Additional verified linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - intrange
    - makezero
    - mirror
    - musttag
    - noctx
    - nolintlint
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - usestdlibvars
    - wastedassign

  disable:
    # Disabled for CLI applications with acceptable use patterns
    - gochecknoinits  # CLI commands use init functions for Cobra setup
    - gosec          # File reading warnings for config loading are acceptable  
    - revive         # Package naming rules too strict for types package
    - tagalign       # Tag alignment too strict for current codebase

  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
  exclude-dirs:
    - vendor
    - bin
    - coverage
    - test_results
  
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
    - ".*_gen\\.go$" 