# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: 'tests/e2e/testdata/flows/error-cases/invalid-json\.json'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.3.0
    hooks:
      - id: golangci-lint
        args: ['run']

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: gofumpt -l -w
        language: system
        types: [go]
        pass_filenames: true

      - id: go-imports
        name: go imports
        entry: goimports -local github.com/ondatra-ai/flow-test-go -w
        language: system
        types: [go]
        pass_filenames: true

      - id: go-test
        name: go test
        entry: bash -c 'go test -v -race $(go list ./... | grep -v "/tests/e2e")'
        language: system
        types: [go]
        pass_filenames: false
