# flow-test-go configuration
app:
  name: flow-test-go
  version: 1.0.0
  debug: false

llm:
  provider: openrouter
  # apiKey: # Set via OPENROUTER_API_KEY environment variable
  defaultModel: openai/gpt-4-turbo
  maxTokens: 4096
  temperature: 0.7
  modelOverrides:
    code-analysis: deepseek/deepseek-chat
    creative: anthropic/claude-3.5-sonnet

github:
  # token: # Set via GITHUB_TOKEN environment variable
  # owner: your-github-username
  # repository: your-repo-name
  defaultBranch: main

flow:
  directory: .flows
  defaultTimeout: 5m
  checkpointDir: .flows/checkpoints
  maxRetries: 3
  enableParallel: true

logging:
  level: info
  format: text
  console: true
  # file: flow-test-go.log
